version: 2.1
orbs:
  multiarch: nanders/multiarch@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - orb-tools/pack:
          filters: *filters
      - multiarch/build_x86_64:
          filters: *filters
          image: "test-multiarch-orb"
          build_context: tests/
      - multiarch/build_arm64:
          filters: *filters
          image: "test-multiarch-orb"
          build_context: tests/
      - multiarch/create_and_push_manifests:
          filters: *filters
          image: "test-multiarch-orb"
          tags: "date timestamp latest"
          requires:
            - multiarch/build_x86_64
            - multiarch/build_arm64
      - orb-tools/publish:
          orb-name: nanders/multiarch
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - multiarch/create_and_push_manifests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
